### ISSUE TITLE
Project: lib_acl_cpp, Configuration: Releasedll Win32 ------ 1>LINK : fatal error LNK1181: cannot open input file 'polarssl.lib'  

### ISSUE THREAD

**Issue by ScottKaiGu** [acl-dev/acl#10]
1>------ Build started: Project: lib_acl_cpp, Configuration: Releasedll Win32 ------
1>LINK : fatal error LNK1181: cannot open input file 'polarssl.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by zhengshuxin** [comment]
The acl's stream module depends the third party library called polarssl, which was put in acl/resource directory.  If you compile lib_acl_cpp.dll, the polarssl.lib will be needed, the reason is that I've define HAS_POLARSSL in comipler preprocessor. Now I've removed the define in the vc project for lib_acl_cpp. If you want to use SSL/TSL comunication in lib_acl_cpp, you should define HAS_POLARSSL in comipler  preprocessor, and include polarssl.lib in your project. The polarssl.lib can be generated by compiling polarssl package in acl/resource.

**Comment by ScottKaiGu** [comment]
many thanks, i've found the src code of polarssl
